version: 2
jobs:
  build1:
    machine: true
    steps:
      - checkout
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: # test what branch we're on.
          name: "What tag"
          command: echo ${CIRCLE_TAG}
  

workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - build1:
          filters:
            tags:
              only: /^v*/
